### ISSUE TITLE
Minor JS fix for "Uncaught TypeError: $ is not a function"

### ISSUE THREAD

**Issue by bpdeconi** [ncstate/ncstate-bootstrap#9]
This isn't a _huge_ issue, but it's an easy fix that would be much appreciated.

When you added [accessible-glyphicons.js](https://github.com/ncstate/ncstate-bootstrap/blob/stable/js/accessible-glyphicons.js), you didn't follow the pattern that the rest of Bootstrap follows, eg.

```javascript
+function ($) {
     'use strict';

     // Code

}(jQuery);
```
Since WordPress uses jQuery in compatibility mode, the accessible-glyphicons portion of bootstrap.min.js generates an `Uncaught TypeError: $ is not a function` error.

I think UComm's projects mostly enqueue jQuery from Google rather than using WP's bundled jQuery, so you don't run into that issue. But there are a couple of reasons we prefer to use WP's jQuery, and this should be an easy fix. accessible-glyphicons is the only place that's causing issues.

**Comment by apmatthews** [comment]
Sounds reasonable to me. Feel free to submit a PR to master. Or I'll try and get to it soon.

**Comment by apmatthews** [comment]
Fix is now on the CDN.

**Comment by bpdeconi** [comment]
Awesome! Thank you @apmatthews!
